"""Piano editoriale annuale: 365 episodi dal 20 aprile 2026."""

from dataclasses import dataclass
from datetime import date


@dataclass
class Episode:
    date: str          # YYYY-MM-DD
    title: str
    description: str   # max 10 parole
    month_theme: str   # tema del mese


PLAN = [
    # Episodio pilota
    Episode("2026-04-19", "Benvenuti al Sommelier Digitale", "Un podcast quotidiano sul vino: cosa aspettarsi", "Fondamentali del vino"),

    # MESE 1: Fondamentali del vino (20 apr – 19 mag)
    Episode("2026-04-20", "Cos'è il vino", "La trasformazione dell'uva in cultura liquida", "Fondamentali del vino"),
    Episode("2026-04-21", "Uva e vino: il legame essenziale", "Come nasce un vino dall'acino", "Fondamentali del vino"),
    Episode("2026-04-22", "Leggere un'etichetta", "Tutto ciò che un'etichetta racconta", "Fondamentali del vino"),
    Episode("2026-04-23", "Il vitigno", "Il DNA che determina il carattere del vino", "Fondamentali del vino"),
    Episode("2026-04-24", "Il terroir", "Suolo, clima e mano dell'uomo nel calice", "Fondamentali del vino"),
    Episode("2026-04-25", "L'annata", "Come il clima cambia il vino ogni anno", "Fondamentali del vino"),
    Episode("2026-04-26", "DOC, DOCG, IGT", "Orientarsi nel sistema delle denominazioni italiane", "Fondamentali del vino"),
    Episode("2026-04-27", "Il colore del vino", "Cosa rivela la tonalità nel bicchiere", "Fondamentali del vino"),
    Episode("2026-04-28", "Il profumo del vino", "Prime parole per descrivere un aroma", "Fondamentali del vino"),
    Episode("2026-04-29", "Il gusto del vino", "Le sensazioni fondamentali in bocca", "Fondamentali del vino"),
    Episode("2026-04-30", "Il tannino", "La struttura che stringe, prosciuga e dura", "Fondamentali del vino"),
    Episode("2026-05-01", "L'acidità", "Il nervo del vino tra freschezza e longevità", "Fondamentali del vino"),
    Episode("2026-05-02", "L'alcol nel vino", "Calore, corpo e impatto sensoriale", "Fondamentali del vino"),
    Episode("2026-05-03", "Il corpo del vino", "Consistenza, peso e struttura percepita", "Fondamentali del vino"),
    Episode("2026-05-04", "La persistenza", "Quanto dura il vino dopo la deglutizione", "Fondamentali del vino"),
    Episode("2026-05-05", "Bianco e rosso: le differenze", "Produzione, uva e carattere a confronto", "Fondamentali del vino"),
    Episode("2026-05-06", "Il vino rosato", "Un vino con una propria identità", "Fondamentali del vino"),
    Episode("2026-05-07", "Gli spumanti", "Bollicine, metodi e differenze essenziali", "Fondamentali del vino"),
    Episode("2026-05-08", "Dolce e secco", "Lo zucchero residuo e come si percepisce", "Fondamentali del vino"),
    Episode("2026-05-09", "Conservare il vino", "Temperature, posizioni e nemici del vino", "Fondamentali del vino"),
    Episode("2026-05-10", "Servire il vino", "Temperature di servizio e scelta del bicchiere", "Fondamentali del vino"),
    Episode("2026-05-11", "Il bicchiere giusto", "Come la forma cambia la percezione del vino", "Fondamentali del vino"),
    Episode("2026-05-12", "Abbinamento: i principi", "Concordanza, contrapposizione e territorialità", "Fondamentali del vino"),
    Episode("2026-05-13", "Abbinamento per concordanza", "Armonie tra cibo e vino che funzionano", "Fondamentali del vino"),
    Episode("2026-05-14", "Abbinamento per contrapposizione", "I contrasti che esaltano entrambi", "Fondamentali del vino"),
    Episode("2026-05-15", "Aprire e decantare", "Tecnica, strumenti e gestione del sedimento", "Fondamentali del vino"),
    Episode("2026-05-16", "I difetti del vino", "Come riconoscere un vino compromesso", "Fondamentali del vino"),
    Episode("2026-05-17", "Il vino al ristorante", "Carta vini, sommelier e scelta consapevole", "Fondamentali del vino"),
    Episode("2026-05-18", "Il vino in enoteca", "Come orientarsi e fare le domande giuste", "Fondamentali del vino"),
    Episode("2026-05-19", "Un mese di fondamentali", "Riepilogo ragionato per ascoltatori esigenti", "Fondamentali del vino"),

    # MESE 2: Vite e vigneto (20 mag – 18 giu)
    Episode("2026-05-20", "La vite", "Anatomia di una pianta millenaria", "Vite e vigneto"),
    Episode("2026-05-21", "Il ciclo vegetativo", "Dormienza, germogliamento, fioritura, raccolta", "Vite e vigneto"),
    Episode("2026-05-22", "La fioritura", "Il momento più delicato dell'anno in vigna", "Vite e vigneto"),
    Episode("2026-05-23", "L'invaiatura", "Il cambio di colore che annuncia la maturazione", "Vite e vigneto"),
    Episode("2026-05-24", "La maturazione dell'uva", "Zuccheri, acidi e polifenoli in movimento", "Vite e vigneto"),
    Episode("2026-05-25", "I suoli del vino", "Argilla, calcare, tufo, ghiaia e basalto", "Vite e vigneto"),
    Episode("2026-05-26", "Il calcare nel vigneto", "Perché i suoli bianchi fanno grandi vini", "Vite e vigneto"),
    Episode("2026-05-27", "I suoli vulcanici", "Mineralità, salinità e identità unica del vulcano", "Vite e vigneto"),
    Episode("2026-05-28", "Il clima del vigneto", "Continentale, oceanico, mediterraneo a confronto", "Vite e vigneto"),
    Episode("2026-05-29", "Le escursioni termiche", "Come il freddo notturno preserva gli aromi", "Vite e vigneto"),
    Episode("2026-05-30", "L'esposizione del vigneto", "Nord, sud, est, ovest: non è indifferente", "Vite e vigneto"),
    Episode("2026-05-31", "L'altitudine in vigna", "Freschezza, acidità e longevità in quota", "Vite e vigneto"),
    Episode("2026-06-01", "La pioggia e la vite", "Quando l'acqua aiuta e quando danneggia", "Vite e vigneto"),
    Episode("2026-06-02", "Le malattie della vite", "Peronospora, oidio, botrite e difese", "Vite e vigneto"),
    Episode("2026-06-03", "La fillossera", "Il parassita che cambiò il vino mondiale", "Vite e vigneto"),
    Episode("2026-06-04", "Le rese in vigna", "Meno uva, vino migliore: è sempre così?", "Vite e vigneto"),
    Episode("2026-06-05", "Potatura e allevamento", "Come si forma la struttura della vite", "Vite e vigneto"),
    Episode("2026-06-06", "Il Guyot", "Il sistema di allevamento più diffuso al mondo", "Vite e vigneto"),
    Episode("2026-06-07", "L'alberello", "Radici profonde e uve concentrate nel caldo", "Vite e vigneto"),
    Episode("2026-06-08", "Pergola e Sylvoz", "Sistemi ad alta resa e il loro impiego", "Vite e vigneto"),
    Episode("2026-06-09", "La viticoltura biologica", "Principi, certificazioni e differenze reali", "Vite e vigneto"),
    Episode("2026-06-10", "La viticoltura biodinamica", "Calendario lunare, preparati e filosofia", "Vite e vigneto"),
    Episode("2026-06-11", "La viticoltura di precisione", "Sensori, droni e big data in vigna", "Vite e vigneto"),
    Episode("2026-06-12", "Il lavoro stagionale in vigna", "Chi lavora la terra e come cambia l'anno", "Vite e vigneto"),
    Episode("2026-06-13", "La vigna vecchia", "Old vines: mito enologico o realtà produttiva?", "Vite e vigneto"),
    Episode("2026-06-14", "I vitigni resistenti PIWI", "La risposta genetica al cambiamento climatico", "Vite e vigneto"),
    Episode("2026-06-15", "Il cambiamento climatico in vigna", "Anticipi, stress idrico e adattamenti", "Vite e vigneto"),
    Episode("2026-06-16", "Biodiversità in vigna", "Erbe, insetti e fauna come indicatori di salute", "Vite e vigneto"),
    Episode("2026-06-17", "Il vigneto come ecosistema", "Una visione integrata e non separata del territorio", "Vite e vigneto"),
    Episode("2026-06-18", "Un mese in vigna", "Riepilogo: dalla terra al carattere del vino", "Vite e vigneto"),

    # MESE 3: Chimica del vino (19 giu – 18 lug)
    Episode("2026-06-19", "La chimica del vino", "Molecole, percezioni e piacere nel bicchiere", "Chimica del vino"),
    Episode("2026-06-20", "Gli zuccheri nell'uva", "Glucosio, fruttosio e la loro trasformazione", "Chimica del vino"),
    Episode("2026-06-21", "La fermentazione alcolica", "Lieviti, zuccheri e la nascita dell'alcol", "Chimica del vino"),
    Episode("2026-06-22", "I lieviti selvaggi", "Fermentazione spontanea: rischio e complessità", "Chimica del vino"),
    Episode("2026-06-23", "I lieviti selezionati", "Sicurezza, prevedibilità e il dibattito aperto", "Chimica del vino"),
    Episode("2026-06-24", "Gli acidi del vino", "Tartarico, malico, lattico: un sistema dinamico", "Chimica del vino"),
    Episode("2026-06-25", "Il pH del vino", "Acidità totale e acidità percepita: la differenza", "Chimica del vino"),
    Episode("2026-06-26", "La fermentazione malolattica", "Da acido aspro a morbidezza burrosa", "Chimica del vino"),
    Episode("2026-06-27", "I tannini in chimica", "Struttura molecolare e sensazione astringente", "Chimica del vino"),
    Episode("2026-06-28", "Gli antociani", "Il colore rosso e la sua evoluzione nel tempo", "Chimica del vino"),
    Episode("2026-06-29", "Gli aromi primari", "I profumi che vengono direttamente dall'uva", "Chimica del vino"),
    Episode("2026-06-30", "Gli aromi secondari", "I profumi nati dalla fermentazione alcolica", "Chimica del vino"),
    Episode("2026-07-01", "Gli aromi terziari", "Il bouquet complesso che nasce dall'affinamento", "Chimica del vino"),
    Episode("2026-07-02", "I tioli varietali", "Pompelmo, passion fruit e ribes: da dove vengono", "Chimica del vino"),
    Episode("2026-07-03", "Le pirazine", "L'aroma erbaceo di Sauvignon Blanc e Cabernet", "Chimica del vino"),
    Episode("2026-07-04", "I terpeni nel vino", "Rosa, litchi e muschio: l'impronta dei vitigni aromatici", "Chimica del vino"),
    Episode("2026-07-05", "Vanillina e lattoni", "Legno, vaniglia e cocco: il contributo del rovere", "Chimica del vino"),
    Episode("2026-07-06", "L'ossidazione del vino", "Quando l'ossigeno trasforma o distrugge", "Chimica del vino"),
    Episode("2026-07-07", "La riduzione del vino", "Difetti solforati e come risolverli", "Chimica del vino"),
    Episode("2026-07-08", "La solforosa nel vino", "Funzione, dosaggi, limiti e controversie", "Chimica del vino"),
    Episode("2026-07-09", "Polifenoli e salute", "Resveratrolo, antiossidanti e verità scientifica", "Chimica del vino"),
    Episode("2026-07-10", "La stabilizzazione del vino", "Tartrati, chiarifica e filtrazione", "Chimica del vino"),
    Episode("2026-07-11", "La chiarifica", "Bentonite, albumina e caseinato: cosa fanno davvero", "Chimica del vino"),
    Episode("2026-07-12", "La filtrazione", "Quando si usa, cosa toglie e cosa lascia", "Chimica del vino"),
    Episode("2026-07-13", "Il colore del bianco", "Da paglierino a dorato: come cambia e perché", "Chimica del vino"),
    Episode("2026-07-14", "Il colore del rosso", "Da rubino a granato: l'evoluzione cromatica nel tempo", "Chimica del vino"),
    Episode("2026-07-15", "Le ammine biogene", "Istamina, tiramina e le reazioni avverse al vino", "Chimica del vino"),
    Episode("2026-07-16", "L'acetato di etile", "Il difetto volatile che sa di acetone e solvente", "Chimica del vino"),
    Episode("2026-07-17", "Il Brettanomyces", "Difetto o carattere? Il Brett che divide i palati", "Chimica del vino"),
    Episode("2026-07-18", "Leggere un'analisi chimica", "Come interpretare i dati di una scheda tecnica", "Chimica del vino"),

    # MESE 4: Produzione e vendemmia (19 lug – 17 ago)
    Episode("2026-07-19", "Quando si vendemmia", "Maturità tecnologica, fenolica e aromatica", "Produzione e vendemmia"),
    Episode("2026-07-20", "Vendemmia a mano e meccanica", "Pro, contro e impatto sulla qualità", "Produzione e vendemmia"),
    Episode("2026-07-21", "La selezione delle uve", "Cernita al tavolo e scelta in vigna", "Produzione e vendemmia"),
    Episode("2026-07-22", "Il trasporto delle uve", "Temperatura, ossigeno e tempo che contano", "Produzione e vendemmia"),
    Episode("2026-07-23", "La pigiatura", "Rottura dell'acino e liberazione del succo", "Produzione e vendemmia"),
    Episode("2026-07-24", "La diraspatura", "Raspo sì, raspo no: una scelta produttiva", "Produzione e vendemmia"),
    Episode("2026-07-25", "Il mosto", "Composizione, densità e gestione nelle prime ore", "Produzione e vendemmia"),
    Episode("2026-07-26", "La macerazione", "Tempo, temperatura ed estrazione dei polifenoli", "Produzione e vendemmia"),
    Episode("2026-07-27", "Il cappello di vinacce", "Gestione e tecniche di rimontaggio", "Produzione e vendemmia"),
    Episode("2026-07-28", "Il délestage", "Travaso e rimontaggio per un'estrazione più gentile", "Produzione e vendemmia"),
    Episode("2026-07-29", "La pressatura", "Torchio, pressa pneumatica e le frazioni di mosto", "Produzione e vendemmia"),
    Episode("2026-07-30", "La fermentazione in bianco", "Temperatura, lieviti e gestione degli aromi", "Produzione e vendemmia"),
    Episode("2026-07-31", "La fermentazione in rosso", "Durata, temperatura e controllo enologico", "Produzione e vendemmia"),
    Episode("2026-08-01", "I contenitori di fermentazione", "Acciaio, legno, cemento, anfora a confronto", "Produzione e vendemmia"),
    Episode("2026-08-02", "L'acciaio in cantina", "Neutralità, controllo termico e pulizia", "Produzione e vendemmia"),
    Episode("2026-08-03", "La barrique", "225 litri di rovere che cambiano il vino", "Produzione e vendemmia"),
    Episode("2026-08-04", "Tonneau e botti grandi", "Meno legno, più integrazione e territorio", "Produzione e vendemmia"),
    Episode("2026-08-05", "Anfora e cemento", "Il ritorno alle origini: texture e mineralità", "Produzione e vendemmia"),
    Episode("2026-08-06", "L'affinamento", "Tempo, micro-ossigenazione e trasformazione", "Produzione e vendemmia"),
    Episode("2026-08-07", "L'affinamento sulle fecce", "Lisi dei lieviti e complessità aromatica", "Produzione e vendemmia"),
    Episode("2026-08-08", "Il bâtonnage", "Rimestare le fecce: quando farlo e perché", "Produzione e vendemmia"),
    Episode("2026-08-09", "Il passaggio in legno", "Come il vino assorbe tannini e aromi dal rovere", "Produzione e vendemmia"),
    Episode("2026-08-10", "Rovere francese e americano", "Due stili, due profili, due risultati enologici", "Produzione e vendemmia"),
    Episode("2026-08-11", "Il taglio enologico", "Il blend come atto creativo e tecnico", "Produzione e vendemmia"),
    Episode("2026-08-12", "L'imbottigliamento", "Filtrazione, dosaggio SO2 e tappatura", "Produzione e vendemmia"),
    Episode("2026-08-13", "Il tappo di sughero", "Pro, contro e il rischio del TCA", "Produzione e vendemmia"),
    Episode("2026-08-14", "I tappi alternativi", "Vite, vetro, DIAM: il dibattito è ancora aperto", "Produzione e vendemmia"),
    Episode("2026-08-15", "L'etichetta e il retro-etichetta", "Informazioni obbligatorie e facoltative", "Produzione e vendemmia"),
    Episode("2026-08-16", "Il confezionamento", "Bottiglia, formato, peso e scelta di mercato", "Produzione e vendemmia"),
    Episode("2026-08-17", "Dalla vigna alla cantina", "Riepilogo del ciclo produttivo completo", "Produzione e vendemmia"),

    # MESE 5: Tipologie di vino (18 ago – 16 set)
    Episode("2026-08-18", "I grandi vini bianchi", "Struttura, longevità e complessità nei bianchi", "Tipologie di vino"),
    Episode("2026-08-19", "I vini bianchi freschi", "Acidità, aromaticità e piacere immediato", "Tipologie di vino"),
    Episode("2026-08-20", "I vini rossi di struttura", "Tannini, corpo e vocazione all'invecchiamento", "Tipologie di vino"),
    Episode("2026-08-21", "I vini rossi da bere giovani", "Frutto, leggerezza e piacere quotidiano", "Tipologie di vino"),
    Episode("2026-08-22", "Il vino rosato", "Tecnica, territorio e pregiudizi da sfatare", "Tipologie di vino"),
    Episode("2026-08-23", "Il Metodo Classico", "Rifermentazione in bottiglia: la presa di spuma", "Tipologie di vino"),
    Episode("2026-08-24", "Il Metodo Charmat", "Autoclave, freschezza e carattere aromatico", "Tipologie di vino"),
    Episode("2026-08-25", "Il Prosecco", "Il vino italiano più venduto al mondo", "Tipologie di vino"),
    Episode("2026-08-26", "Il Franciacorta", "L'ambizione italiana al vertice degli spumanti", "Tipologie di vino"),
    Episode("2026-08-27", "Il Trento DOC", "Alta montagna, finezza e identità alpina", "Tipologie di vino"),
    Episode("2026-08-28", "Il Champagne", "Storia, stile e una supremazia costruita nel tempo", "Tipologie di vino"),
    Episode("2026-08-29", "I passiti", "Appassimento, concentrazione e dolcezza complessa", "Tipologie di vino"),
    Episode("2026-08-30", "I vini muffati", "Botrytis cinerea: il fungo che fa grandi dolci", "Tipologie di vino"),
    Episode("2026-08-31", "Il Vin Santo", "Caratelli, lunghi affinamenti e tradizione toscana", "Tipologie di vino"),
    Episode("2026-09-01", "I vini da appassimento", "Amarone, Sforzato e lo stile veneto", "Tipologie di vino"),
    Episode("2026-09-02", "Gli orange wines", "Macerazione sulle bucce per i vini bianchi", "Tipologie di vino"),
    Episode("2026-09-03", "I vini naturali", "Definizione, filosofia e controversie aperte", "Tipologie di vino"),
    Episode("2026-09-04", "I vini biodinamici in bottiglia", "Dal vigneto alla bottiglia senza additivi", "Tipologie di vino"),
    Episode("2026-09-05", "I pétillant naturels", "Il metodo ancestrale e il fascino dell'imprevedibile", "Tipologie di vino"),
    Episode("2026-09-06", "I vini ossidativi", "Manzanilla, Vin Jaune e il fascino dell'ossidazione", "Tipologie di vino"),
    Episode("2026-09-07", "I vini liquorosi", "Porto, Sherry, Marsala: mutizzazione e potenza", "Tipologie di vino"),
    Episode("2026-09-08", "Il Porto", "Stili, invecchiamento e la Douro Valley", "Tipologie di vino"),
    Episode("2026-09-09", "Lo Sherry", "Il grande incompreso della Spagna enologica", "Tipologie di vino"),
    Episode("2026-09-10", "Il Marsala", "Storia, declino e le ragioni di una possibile rinascita", "Tipologie di vino"),
    Episode("2026-09-11", "I vini da meditazione", "Quando il vino non ha bisogno del cibo", "Tipologie di vino"),
    Episode("2026-09-12", "Versatilità come qualità", "Vini da tutto pasto: adattabilità come virtù", "Tipologie di vino"),
    Episode("2026-09-13", "Il vino al calice", "Economia, selezione e uso professionale", "Tipologie di vino"),
    Episode("2026-09-14", "Il vino dealcolato", "Tecnologie di dealcolazione e mercato emergente", "Tipologie di vino"),
    Episode("2026-09-15", "Vino e cocktail", "Spritz, Kir e l'uso del vino in mixology", "Tipologie di vino"),
    Episode("2026-09-16", "Panorama delle tipologie", "Un riepilogo utile per orientarsi sempre meglio", "Tipologie di vino"),

    # MESE 6: Territori italiani (17 set – 16 ott)
    Episode("2026-09-17", "L'Italia del vino", "20 regioni, 350 vitigni, un'identità plurale", "Territori italiani"),
    Episode("2026-09-18", "Il Piemonte", "Nebbiolo, Barolo e la grandezza del Nord-Ovest", "Territori italiani"),
    Episode("2026-09-19", "Il Barolo", "Il re dei vini italiani: storia, sottozone e stili", "Territori italiani"),
    Episode("2026-09-20", "Il Barbaresco", "Eleganza e precocità del Nebbiolo d'Alba", "Territori italiani"),
    Episode("2026-09-21", "Il Barbera d'Asti", "Il vino quotidiano del Piemonte diventato grande", "Territori italiani"),
    Episode("2026-09-22", "Il Moscato d'Asti", "Dolcezza, leggerezza e un territorio delicato", "Territori italiani"),
    Episode("2026-09-23", "Valle d'Aosta e Liguria", "Viticoltura eroica tra ghiacciai e mare", "Territori italiani"),
    Episode("2026-09-24", "La Lombardia", "Franciacorta, Valtellina e la diversità lombarda", "Territori italiani"),
    Episode("2026-09-25", "La Valtellina", "Nebbiolo in quota: Sforzato e Sassella", "Territori italiani"),
    Episode("2026-09-26", "Il Trentino-Alto Adige", "Precisione alpina e vitigni internazionali", "Territori italiani"),
    Episode("2026-09-27", "Il Veneto", "Amarone, Soave, Prosecco: tre anime in una regione", "Territori italiani"),
    Episode("2026-09-28", "L'Amarone della Valpolicella", "Appassimento, concentrazione e grandezza", "Territori italiani"),
    Episode("2026-09-29", "Il Soave", "Garganega e vulcano: un bianco da riscoprire", "Territori italiani"),
    Episode("2026-09-30", "Il Friuli-Venezia Giulia", "Bianchi strutturati e identità di confine", "Territori italiani"),
    Episode("2026-10-01", "L'Emilia-Romagna", "Lambrusco, Sangiovese e la cultura del convivio", "Territori italiani"),
    Episode("2026-10-02", "Il Lambrusco", "Bollicine rosse emiliane: storia e pieno riscatto", "Territori italiani"),
    Episode("2026-10-03", "La Toscana", "Sangiovese e il territorio più celebre del mondo", "Territori italiani"),
    Episode("2026-10-04", "Il Chianti Classico", "Gallo Nero, annate e la mappa delle sottozone", "Territori italiani"),
    Episode("2026-10-05", "Il Brunello di Montalcino", "Il vino italiano con la longevità più estrema", "Territori italiani"),
    Episode("2026-10-06", "Il Vino Nobile di Montepulciano", "Prugnolo gentile e una storia davvero nobile", "Territori italiani"),
    Episode("2026-10-07", "I Supertuscan", "Come il Sassicaia cambiò le regole del gioco", "Territori italiani"),
    Episode("2026-10-08", "La Vernaccia di San Gimignano", "Il primo DOC d'Italia e la sua storia", "Territori italiani"),
    Episode("2026-10-09", "Le Marche e l'Umbria", "Verdicchio, Sagrantino e l'Italia centrale", "Territori italiani"),
    Episode("2026-10-10", "Il Sagrantino di Montefalco", "Il vitigno con il tannino più potente d'Italia", "Territori italiani"),
    Episode("2026-10-11", "L'Abruzzo", "Montepulciano e Trebbiano: generosità adriatica", "Territori italiani"),
    Episode("2026-10-12", "Il Lazio e la Campania", "Frascati, Fiano, Greco e la rinascita del Sud", "Territori italiani"),
    Episode("2026-10-13", "Il Taurasi", "L'Aglianico al suo vertice nel cuore campano", "Territori italiani"),
    Episode("2026-10-14", "Puglia e Basilicata", "Primitivo, Negroamaro e Aglianico del Vulture", "Territori italiani"),
    Episode("2026-10-15", "La Sicilia", "Etna, Nero d'Avola e la rivoluzione enologica", "Territori italiani"),
    Episode("2026-10-16", "La Sardegna", "Cannonau, Vermentino e un'identità insulare forte", "Territori italiani"),

    # MESE 7: Territori internazionali (17 ott – 15 nov)
    Episode("2026-10-17", "La Francia: introduzione", "Il sistema AOC e la logica del territorio", "Territori internazionali"),
    Episode("2026-10-18", "La Borgogna", "Pinot Noir, Chardonnay e il concetto di climat", "Territori internazionali"),
    Episode("2026-10-19", "Bordeaux", "Cabernet, Merlot e la tradizione del grande blend", "Territori internazionali"),
    Episode("2026-10-20", "Il Rodano", "Syrah al nord, Grenache al sud, blend ovunque", "Territori internazionali"),
    Episode("2026-10-21", "La Loira", "Muscadet, Sancerre, Vouvray: diversità in un fiume", "Territori internazionali"),
    Episode("2026-10-22", "L'Alsazia", "Riesling, Gewürztraminer e lo stile di frontiera", "Territori internazionali"),
    Episode("2026-10-23", "Il Champagne: territorio", "Maison, grower e le tre anime delle bollicine", "Territori internazionali"),
    Episode("2026-10-24", "Il Languedoc-Roussillon", "Mare, sole e i vini del Sud della Francia", "Territori internazionali"),
    Episode("2026-10-25", "La Spagna: introduzione", "Rioja, Ribera del Duero e una diversità enorme", "Territori internazionali"),
    Episode("2026-10-26", "La Rioja", "Tempranillo, crianza e la tradizione del rovere", "Territori internazionali"),
    Episode("2026-10-27", "La Ribera del Duero", "Altitudine, potenza e i grandi rossi di Castiglia", "Territori internazionali"),
    Episode("2026-10-28", "Il Priorat", "Garnacha su llicorella: concentrazione ai limiti", "Territori internazionali"),
    Episode("2026-10-29", "La Germania: il Riesling", "Dolce, secco, sublime: tre anime di un vitigno", "Territori internazionali"),
    Episode("2026-10-30", "Il Mosel", "Ardesia, freschezza e i Riesling più longevi al mondo", "Territori internazionali"),
    Episode("2026-10-31", "Il Portogallo", "Oltre il Porto: Alentejo, Dão e Vinho Verde", "Territori internazionali"),
    Episode("2026-11-01", "L'Alentejo", "Il grande serbatoio del vino portoghese moderno", "Territori internazionali"),
    Episode("2026-11-02", "L'Austria", "Grüner Veltliner e Riesling: la precisione danubiana", "Territori internazionali"),
    Episode("2026-11-03", "La Georgia", "La culla del vino: anfora, qvevri e ottomila anni", "Territori internazionali"),
    Episode("2026-11-04", "La Grecia", "Assyrtiko, Xinomavro e la rinascita enologica ellenica", "Territori internazionali"),
    Episode("2026-11-05", "Il Nuovo Mondo: introduzione", "California, Cile, Argentina e Australia", "Territori internazionali"),
    Episode("2026-11-06", "La California", "Napa Valley, Sonoma e il Cabernet californiano", "Territori internazionali"),
    Episode("2026-11-07", "L'Argentina", "Malbec, Mendoza e la viticoltura d'alta quota", "Territori internazionali"),
    Episode("2026-11-08", "Il Cile", "Carménère, valle centrale e la vocazione del Pacifico", "Territori internazionali"),
    Episode("2026-11-09", "L'Australia", "Shiraz, Barossa e l'identità del Nuovo Mondo australe", "Territori internazionali"),
    Episode("2026-11-10", "Il Sudafrica", "Pinotage, Stellenbosch e il Chenin Blanc ritrovato", "Territori internazionali"),
    Episode("2026-11-11", "La Nuova Zelanda", "Sauvignon Blanc, Pinot Noir e la purezza di Marlborough", "Territori internazionali"),
    Episode("2026-11-12", "Europa centrale ed Est", "Slovenia, Croazia, Ungheria: confini da esplorare", "Territori internazionali"),
    Episode("2026-11-13", "Il Tokaji", "Aszú, botrite e la nobiltà storica dell'Ungheria", "Territori internazionali"),
    Episode("2026-11-14", "Vecchio e Nuovo Mondo", "Filosofie, stili e convergenze in atto", "Territori internazionali"),
    Episode("2026-11-15", "La mappa del vino nel mondo", "Un riepilogo geografico per orientarsi sempre", "Territori internazionali"),

    # MESE 8: Vitigni (16 nov – 15 dic)
    Episode("2026-11-16", "I grandi vitigni: introduzione", "Internazionali, autoctoni, rari e dimenticati", "Vitigni"),
    Episode("2026-11-17", "Il Cabernet Sauvignon", "Il vitigno più piantato al mondo: storia e carattere", "Vitigni"),
    Episode("2026-11-18", "Il Merlot", "Morbidezza, accessibilità e la grandezza di Pomerol", "Vitigni"),
    Episode("2026-11-19", "Il Pinot Noir", "Eleganza fragile e complessità insuperabile", "Vitigni"),
    Episode("2026-11-20", "Il Syrah e lo Shiraz", "Nord Rodano contro Australia: un vitigno, due anime", "Vitigni"),
    Episode("2026-11-21", "Il Grenache e la Garnacha", "Potenza, frutto e calore mediterraneo", "Vitigni"),
    Episode("2026-11-22", "Il Sangiovese", "Dal Chianti al Brunello: il cuore del vino italiano", "Vitigni"),
    Episode("2026-11-23", "Il Nebbiolo", "Tannino, acidità e la grandezza piemontese", "Vitigni"),
    Episode("2026-11-24", "L'Aglianico", "Il Barolo del Sud: struttura e longevità meridionale", "Vitigni"),
    Episode("2026-11-25", "Il Montepulciano", "Versatile, generoso e ancora sottovalutato", "Vitigni"),
    Episode("2026-11-26", "Il Primitivo e lo Zinfandel", "Dalle Puglie alla California: un vitigno, due storie", "Vitigni"),
    Episode("2026-11-27", "Il Nero d'Avola", "Calore siciliano concentrato in un vitigno", "Vitigni"),
    Episode("2026-11-28", "Il Nerello Mascalese", "L'eleganza etnea che sorprende il mondo", "Vitigni"),
    Episode("2026-11-29", "Il Cannonau", "Sardegna, longevità e il mistero della zona blu", "Vitigni"),
    Episode("2026-11-30", "Il Chardonnay", "Il vitigno bianco più versatile e interpretato al mondo", "Vitigni"),
    Episode("2026-12-01", "Il Sauvignon Blanc", "Aromi tiolitici, stili e territori d'elezione", "Vitigni"),
    Episode("2026-12-02", "Il Riesling", "Acidità, longevità e la nobiltà del bianco tedesco", "Vitigni"),
    Episode("2026-12-03", "Il Pinot Grigio e il Pinot Gris", "Da vino commerciale a grande espressione", "Vitigni"),
    Episode("2026-12-04", "Il Gewürztraminer", "Spezie, rosa e la polarizzazione dei degustatori", "Vitigni"),
    Episode("2026-12-05", "Il Vermentino", "Mediterraneo, salinità e l'identità sarda", "Vitigni"),
    Episode("2026-12-06", "Il Verdicchio", "Acidità, struttura e il grande bianco marchigiano", "Vitigni"),
    Episode("2026-12-07", "Il Greco di Tufo", "Mineralità campana e storia millenaria", "Vitigni"),
    Episode("2026-12-08", "Il Fiano di Avellino", "Complessità, longevità e unicità irpina", "Vitigni"),
    Episode("2026-12-09", "La Garganega", "Soave e il territorio vulcanico veronese", "Vitigni"),
    Episode("2026-12-10", "Il Glera e il Prosecco", "Dal vitigno al vino più venduto d'Italia", "Vitigni"),
    Episode("2026-12-11", "Il Moscato Bianco", "Aromaticità, dolcezza e territorialità", "Vitigni"),
    Episode("2026-12-12", "L'Assyrtiko", "Santorini, vulcano e la mineralità assoluta", "Vitigni"),
    Episode("2026-12-13", "Vitigni rari e autoctoni", "Il patrimonio ampelografico italiano da salvare", "Vitigni"),
    Episode("2026-12-14", "Riconoscere i vitigni", "Strumenti sensoriali per identificarli alla cieca", "Vitigni"),
    Episode("2026-12-15", "Vitigni e clima che cambia", "Adattamento, rischio e nuove geografie del vino", "Vitigni"),

    # MESE 9: Degustazione e percezione (16 dic – 14 gen)
    Episode("2026-12-16", "L'arte della degustazione", "Metodo, disciplina e il piacere del dettaglio", "Degustazione e percezione"),
    Episode("2026-12-17", "L'esame visivo", "Limpidezza, colore, consistenza e lacrime nel bicchiere", "Degustazione e percezione"),
    Episode("2026-12-18", "L'esame olfattivo", "Come annusare un vino con metodo e attenzione", "Degustazione e percezione"),
    Episode("2026-12-19", "L'esame gustativo", "Le sensazioni in bocca analizzate una per una", "Degustazione e percezione"),
    Episode("2026-12-20", "Il metodo AIS", "La degustazione sistematica italiana", "Degustazione e percezione"),
    Episode("2026-12-21", "La scheda di degustazione", "Come compilarla e usarla davvero", "Degustazione e percezione"),
    Episode("2026-12-22", "L'acidità in bocca", "Salivazione, freschezza e abbinamento guidato", "Degustazione e percezione"),
    Episode("2026-12-23", "Il tannino in degustazione", "Astringenza, durezza e grana percepita", "Degustazione e percezione"),
    Episode("2026-12-24", "L'alcol in degustazione", "Calore, corpo e la destabilizzazione dell'equilibrio", "Degustazione e percezione"),
    Episode("2026-12-25", "La dolcezza percepita", "Zucchero residuo, glicerina e sensazione morbida", "Degustazione e percezione"),
    Episode("2026-12-26", "Il corpo in degustazione", "Leggerezza, medio corpo e piena struttura", "Degustazione e percezione"),
    Episode("2026-12-27", "La persistenza aromatica", "IPA e la misura di un finale davvero lungo", "Degustazione e percezione"),
    Episode("2026-12-28", "L'equilibrio del vino", "Quando tutti gli elementi trovano il loro posto", "Degustazione e percezione"),
    Episode("2026-12-29", "La complessità", "Quante cose riesce a dire un vino in un sorso", "Degustazione e percezione"),
    Episode("2026-12-30", "La tipicità", "Riconoscere un territorio e un vitigno da un sorso", "Degustazione e percezione"),
    Episode("2026-12-31", "L'evoluzione del vino", "Come cambia in bottiglia con il passare del tempo", "Degustazione e percezione"),
    Episode("2027-01-01", "Il vino e la memoria", "Perché certi vini restano impressi per sempre", "Degustazione e percezione"),
    Episode("2027-01-02", "I difetti in degustazione", "Come riconoscerli, nominarli e gestirli", "Degustazione e percezione"),
    Episode("2027-01-03", "Il TCA e il tappo", "Il difetto più comune e come riconoscerlo", "Degustazione e percezione"),
    Episode("2027-01-04", "Costruire la memoria olfattiva", "Esercizi pratici per allenare il naso", "Degustazione e percezione"),
    Episode("2027-01-05", "Degustare alla cieca", "Metodo, errori comuni e cosa si impara davvero", "Degustazione e percezione"),
    Episode("2027-01-06", "Riconoscere i bianchi alla cieca", "Esercizio guidato sui vitigni bianchi principali", "Degustazione e percezione"),
    Episode("2027-01-07", "Riconoscere i rossi alla cieca", "Esercizio guidato sui vitigni rossi principali", "Degustazione e percezione"),
    Episode("2027-01-08", "Degustare uno spumante", "Bollicine, complessità e parametri specifici", "Degustazione e percezione"),
    Episode("2027-01-09", "Degustare un passito", "Dolcezza, acidità e longevità a confronto", "Degustazione e percezione"),
    Episode("2027-01-10", "Degustare un vino invecchiato", "Evoluzione, sofisticazione e lettura del tempo", "Degustazione e percezione"),
    Episode("2027-01-11", "Il linguaggio del vino", "Come descrivere senza banalizzare né esagerare", "Degustazione e percezione"),
    Episode("2027-01-12", "I descrittori aromatici", "Un vocabolario preciso e utile per comunicare", "Degustazione e percezione"),
    Episode("2027-01-13", "Punteggi e guide", "Come leggere le valutazioni senza esserne dipendenti", "Degustazione e percezione"),
    Episode("2027-01-14", "Diventare un degustatore", "Il percorso lento verso la padronanza sensoriale", "Degustazione e percezione"),

    # MESE 10: Storia del vino (15 gen – 13 feb)
    Episode("2027-01-15", "Le origini del vino", "Georgia, Iran e ottomila anni di storia fermentata", "Storia del vino"),
    Episode("2027-01-16", "Il vino nell'antico Egitto", "Produzione, commercio e rituali funerari", "Storia del vino"),
    Episode("2027-01-17", "Il vino nella Grecia antica", "Simposio, Dioniso e la cultura del calice", "Storia del vino"),
    Episode("2027-01-18", "I Romani e il vino", "Anfore, Falerno e il commercio imperiale", "Storia del vino"),
    Episode("2027-01-19", "Il vino nel Medioevo", "Monaci, ospedali e la sopravvivenza del vino", "Storia del vino"),
    Episode("2027-01-20", "I Cistercensi e la Borgogna", "Come i monaci inventarono il concetto di cru", "Storia del vino"),
    Episode("2027-01-21", "Il vino e le rotte commerciali", "Venezia, Bordeaux e i mercanti medievali", "Storia del vino"),
    Episode("2027-01-22", "Il Porto e gli inglesi", "Come nacque un vino liquoroso dal commercio", "Storia del vino"),
    Episode("2027-01-23", "Dom Pérignon e le bollicine", "Mito, storia e la nascita del Champagne", "Storia del vino"),
    Episode("2027-01-24", "La classificazione di Bordeaux", "1855: come nacque una gerarchia immortale", "Storia del vino"),
    Episode("2027-01-25", "La fillossera", "Il parassita che devastò e poi trasformò il vino europeo", "Storia del vino"),
    Episode("2027-01-26", "La ricostruzione post-fillossera", "Innesti, varietà e nuovi sistemi di allevamento", "Storia del vino"),
    Episode("2027-01-27", "La nascita delle denominazioni", "AOC, DOC e il controllo d'origine nel Novecento", "Storia del vino"),
    Episode("2027-01-28", "Il vino nel Novecento", "Industrializzazione, crisi e modernità enologica", "Storia del vino"),
    Episode("2027-01-29", "La California enologica", "Come la California sfidò e ridisegnò il vino mondiale", "Storia del vino"),
    Episode("2027-01-30", "Il Giudizio di Parigi 1976", "La degustazione cieca che cambiò il mondo del vino", "Storia del vino"),
    Episode("2027-01-31", "La rivoluzione italiana", "Sassicaia, Tignanello e il rinascimento degli anni '80", "Storia del vino"),
    Episode("2027-02-01", "Robert Parker e la critica", "Il potere di un palato nella storia del vino", "Storia del vino"),
    Episode("2027-02-02", "L'internazionalizzazione del gusto", "Verso un vino globale e le resistenze locali", "Storia del vino"),
    Episode("2027-02-03", "La contro-rivoluzione naturale", "Dal vino tecnico al vino vivo: una frattura culturale", "Storia del vino"),
    Episode("2027-02-04", "Storia del vino biologico", "Da scelta marginale a mercato in crescita", "Storia del vino"),
    Episode("2027-02-05", "Rudolf Steiner e il vino", "La biodinamica: da filosofia a pratica certificata", "Storia del vino"),
    Episode("2027-02-06", "Storia del Barolo", "Da vino dolce semidolce al re dei vini italiani", "Storia del vino"),
    Episode("2027-02-07", "Storia del Chianti", "Dal fiasco di paglia all'eccellenza mondiale", "Storia del vino"),
    Episode("2027-02-08", "Storia del Brunello", "Biondi Santi e la costruzione paziente di un mito", "Storia del vino"),
    Episode("2027-02-09", "Storia del Prosecco", "Da vino locale di frontiera a fenomeno globale", "Storia del vino"),
    Episode("2027-02-10", "Le grandi annate storiche", "Le bottiglie che hanno scritto la storia del vino", "Storia del vino"),
    Episode("2027-02-11", "Il vino nella letteratura", "Da Omero a Pavese: il vino come metafora", "Storia del vino"),
    Episode("2027-02-12", "Il vino nell'arte", "Bacco, Caravaggio e la rappresentazione del vino", "Storia del vino"),
    Episode("2027-02-13", "Cent'anni di vino italiano", "Un secolo di trasformazioni, conquiste e cadute", "Storia del vino"),

    # MESE 11: Economia del vino (14 feb – 15 mar)
    Episode("2027-02-14", "Economia del vino: introduzione", "Un mercato globale da 350 miliardi di euro", "Economia del vino"),
    Episode("2027-02-15", "Il costo di un vino", "Dalla vigna allo scaffale: tutti i passaggi economici", "Economia del vino"),
    Episode("2027-02-16", "Il pricing del vino", "Come si fissa il prezzo di una bottiglia", "Economia del vino"),
    Episode("2027-02-17", "Il valore percepito", "Perché paghiamo di più per certi vini", "Economia del vino"),
    Episode("2027-02-18", "La cantina come impresa", "Investimenti, rischi e ritorno economico", "Economia del vino"),
    Episode("2027-02-19", "Il ruolo del distributore", "Dalla cantina all'enoteca: la catena di valore", "Economia del vino"),
    Episode("2027-02-20", "Il vino nella GDO", "Supermercato: dati di consumo e qualità reale", "Economia del vino"),
    Episode("2027-02-21", "L'enoteca indipendente", "Selezione, consulenza e sopravvivenza commerciale", "Economia del vino"),
    Episode("2027-02-22", "Il canale HORECA", "Ristoranti, hotel e bar come mercato del vino", "Economia del vino"),
    Episode("2027-02-23", "La carta dei vini", "Come costruire una carta vini profittevole e coerente", "Economia del vino"),
    Episode("2027-02-24", "L'export del vino italiano", "Mercati, trend e competitor internazionali", "Economia del vino"),
    Episode("2027-02-25", "Il vino italiano negli USA", "Il mercato più importante: numeri e strategie", "Economia del vino"),
    Episode("2027-02-26", "Il vino in Asia", "Cina, Giappone e i nuovi consumatori orientali", "Economia del vino"),
    Episode("2027-02-27", "Il branding territoriale", "Come un nome diventa valore economico", "Economia del vino"),
    Episode("2027-02-28", "I Consorzi di tutela", "Funzione, potere politico e limiti operativi", "Economia del vino"),
    Episode("2027-03-01", "Le aste di vino", "Christie's, Sotheby's e il vino come investimento", "Economia del vino"),
    Episode("2027-03-02", "Il collezionismo di vino", "Cantina, conservazione e speculazione", "Economia del vino"),
    Episode("2027-03-03", "Il mercato dei vini rari", "Petrus, DRC e le quotazioni dell'irraggiungibile", "Economia del vino"),
    Episode("2027-03-04", "Il vino contraffatto", "Frodi, falsi e come il mercato si difende", "Economia del vino"),
    Episode("2027-03-05", "I consumi contemporanei", "Meno ma meglio: la nuova demografia del vino", "Economia del vino"),
    Episode("2027-03-06", "I millennial e il vino", "Nuovi comportamenti, valori e canali d'acquisto", "Economia del vino"),
    Episode("2027-03-07", "La sostenibilità economica", "Fare impresa vinicola in modo duraturo", "Economia del vino"),
    Episode("2027-03-08", "Il vino sfuso e il bag-in-box", "Tradizione, risparmio e sostenibilità ambientale", "Economia del vino"),
    Episode("2027-03-09", "Il Direct-to-Consumer", "Come le cantine vendono direttamente e perché", "Economia del vino"),
    Episode("2027-03-10", "L'enoturismo", "Il wine tourism come leva economica e culturale", "Economia del vino"),
    Episode("2027-03-11", "Il vino online", "E-commerce, abbonamenti e nuovi modelli di vendita", "Economia del vino"),
    Episode("2027-03-12", "Trend emergenti", "Low alcol, naturale ed esperienziale: dove va il vino", "Economia del vino"),
    Episode("2027-03-13", "Il futuro del mercato", "Previsioni, sfide e opportunità per i prossimi anni", "Economia del vino"),
    Episode("2027-03-14", "Fare impresa nel vino", "Lezioni da chi ha costruito qualcosa di duraturo", "Economia del vino"),
    Episode("2027-03-15", "Un anno di economia", "Riepilogo: dal prezzo alla cantina, al futuro", "Economia del vino"),

    # MESE 12: Integrazione avanzata (16 mar – 19 apr)
    Episode("2027-03-16", "L'identità del vino", "Territorio, vitigno e uomo: chi fa davvero il vino", "Integrazione avanzata"),
    Episode("2027-03-17", "Il vino e la gastronomia italiana", "Un patrimonio unico e inscindibile", "Integrazione avanzata"),
    Episode("2027-03-18", "Abbinare i grandi rossi", "Barolo, Brunello e Amarone a tavola", "Integrazione avanzata"),
    Episode("2027-03-19", "Abbinare i grandi bianchi", "Borgogna, Riesling e Fiano a tavola", "Integrazione avanzata"),
    Episode("2027-03-20", "Abbinare gli spumanti", "Dalla colazione al dessert: versatilità delle bollicine", "Integrazione avanzata"),
    Episode("2027-03-21", "Vino e formaggio", "Un classico con regole proprie e mille eccezioni", "Integrazione avanzata"),
    Episode("2027-03-22", "Vino e pesce", "Bianchi, rosati e qualche rosso leggero in tavola", "Integrazione avanzata"),
    Episode("2027-03-23", "Vino e carne", "Struttura, tannino e cottura: come scegliere", "Integrazione avanzata"),
    Episode("2027-03-24", "Vino e dolci", "La sfida più difficile dell'abbinamento enogastronomico", "Integrazione avanzata"),
    Episode("2027-03-25", "Vino e pizza", "Un abbinamento tutto italiano da prendere sul serio", "Integrazione avanzata"),
    Episode("2027-03-26", "Vino e cioccolato", "Contrasti, sorprese e i binomi che funzionano", "Integrazione avanzata"),
    Episode("2027-03-27", "Costruire una cantina domestica", "Selezione, spazio e investimento ragionato", "Integrazione avanzata"),
    Episode("2027-03-28", "Leggere una carta dei vini", "Strategia, orientamento e come non perdersi", "Integrazione avanzata"),
    Episode("2027-03-29", "Scegliere in enoteca", "Le domande giuste per trovare il vino giusto", "Integrazione avanzata"),
    Episode("2027-03-30", "Scegliere al ristorante", "Abbinamento, budget e il rapporto col sommelier", "Integrazione avanzata"),
    Episode("2027-03-31", "Regalare un vino", "Occasioni, scelte intelligenti e presentazione", "Integrazione avanzata"),
    Episode("2027-04-01", "Il vino e le emozioni", "Perché certi vini toccano corde che altri non raggiungono", "Integrazione avanzata"),
    Episode("2027-04-02", "I grandi degustatori", "Broadbent, Johnson, Parker: palati che hanno fatto storia", "Integrazione avanzata"),
    Episode("2027-04-03", "Produttori che hanno cambiato tutto", "Ritratti di chi ha ridisegnato il vino mondiale", "Integrazione avanzata"),
    Episode("2027-04-04", "Il vino e la tecnologia", "Innovazione, app e il futuro digitale del settore", "Integrazione avanzata"),
    Episode("2027-04-05", "Il vino e l'intelligenza artificiale", "Analisi, previsioni e limiti dell'algoritmo", "Integrazione avanzata"),
    Episode("2027-04-06", "Il vino e il viaggio", "Come degustare un territorio visitandolo davvero", "Integrazione avanzata"),
    Episode("2027-04-07", "Costruire il proprio palato", "Un percorso personale verso la padronanza", "Integrazione avanzata"),
    Episode("2027-04-08", "Il vino e la convivialità", "Bere insieme come atto culturale e umano", "Integrazione avanzata"),
    Episode("2027-04-09", "Il vino e la spiritualità", "Da Dioniso alla Messa: il vino sacro nelle culture", "Integrazione avanzata"),
    Episode("2027-04-10", "Il vino e la scienza", "Neurologia del gusto e ricerca contemporanea", "Integrazione avanzata"),
    Episode("2027-04-11", "Il vino e il linguaggio", "Come parlare di vino senza ridicolizzarsi", "Integrazione avanzata"),
    Episode("2027-04-12", "Una biblioteca del vino", "Libri, guide e fonti autorevoli da conoscere", "Integrazione avanzata"),
    Episode("2027-04-13", "Il vino come cultura", "Al di là del bicchiere: un universo di significati", "Integrazione avanzata"),
    Episode("2027-04-14", "Bottiglie da bere almeno una volta", "Una lista personale e motivata", "Integrazione avanzata"),
    Episode("2027-04-15", "Il sommelier", "Una professione tra arte, scienza e servizio", "Integrazione avanzata"),
    Episode("2027-04-16", "Diventare sommelier", "Percorsi, esami e riconoscimenti internazionali", "Integrazione avanzata"),
    Episode("2027-04-17", "Il vino nel cinema", "Rappresentazioni, stereotipi e scene memorabili", "Integrazione avanzata"),
    Episode("2027-04-18", "L'eredità del vino", "Cosa lasciamo alla generazione che verrà", "Integrazione avanzata"),
    Episode("2027-04-19", "Un anno con il vino", "Bilancio finale, gratitudine e arrivederci", "Integrazione avanzata"),
]

_INDEX = {ep.date: ep for ep in PLAN}


def get_episode(d: date | str | None = None) -> Episode | None:
    from datetime import date as date_type
    if d is None:
        from datetime import datetime, timezone
        d = datetime.now(timezone.utc).date()
    if isinstance(d, date_type):
        d = d.strftime("%Y-%m-%d")
    return _INDEX.get(d)
